name : Feature Request
description : Request a new feature
labels : ["request"]

body :
  - type : markdown
    attributes :
      value : "Please note that v2 of Carsa's Commands is intended to the final version. It is unlikely that features will be added but we are still open to ideas."
  - type : textarea
    id : feature-description
    attributes :
      label : Feature Description
      description : Please describe your feature as clearly as possible.
  - type : markdown
    attributes :
      value : |
        "Thank you for contributing to Carsa's Commands v2!"